auth:
  wcl_client:
    client_id: "not-set"      # read from env var "WCL_CLIENT_ID
    client_secret: "not-set"  # read from env var "WCL_CLIENT_SECRET"
    token_url: "https://www.warcraftlogs.com/oauth/token"
    api_endpoint: "https://www.warcraftlogs.com/api/v2/client"

season:
  key: dfs3
  name: Dragonflight - Season 3

player:
  - name: Carmen
    chars: ["Cheîra-Aman'thul"]
  - name: Christoph
    chars: ["Thýráel-Antonidas","Thyraldur-Blackhand","Thyrân-Antonidas","Thyrodor-Antonidas","Thyrondir-Antonidas"]
  - name: Dave
    chars: ["Schorsé-Antonidas","Failpuller-Antonidas","Angstblasé-Antonidas"]
  - name: Dennis
    chars: ["Mirady-Antonidas"]
  - name: Dimi
    chars: ["Fanfaron-Dalvengyr"]
  - name: Franzi
    chars: ["Lelu-Anub'arak"]
  - name: Janine
    chars: ["Motsognir-Anub'arak"]
  - name: Jessica
    chars: ["Roselyn-Aman'thul"]
  - name: Joseph
    chars: ["Etegosch-Zuluhed"]
  - name: Kalle
    chars: ["Gameofthrows-Blackhand","Gameofthrows-Antonidas"]
  - name: Kevin
    chars: ["Xenqt-Blackhand","Xenzqt-Blackhand","Heartdivine-Blackhand"]
  - name: Leon
    chars: ["Gómèz-Antonidas","Sancticia-Antonidas","Simplecia-Antonidas"]
  - name: Lutz
    chars: ["Jnx-Aman'thul","Pokusan-Aman'thul"]
  - name: Marco
    chars: ["Nay-Anub'arak","Fadrim-Anub'arak"]
  - name: Marc
    chars: ["Seysey-Aman'thul","Loryxius-Aman'thul"]
  - name: Maxi
    chars: ["Zhòrá-Thrall","Zhòráqt-Thrall"]
  - name: Micha
    chars: ["Wurzelpeter-Anub'arak"]
  - name: Mischa
    chars: ["Kellykiller-Aman'thul"]
  - name: Olli
    chars: ["Moppi-Anub'arak", "Zelma-Anub'arak"]
  - name: Stephan
    chars: ["Madherby-Nazjatar"]
  - name: Tanja
    chars: ["Blair-Dalvengyr","Icheule-Anub'arak"]
  - name: Thomas
    chars: ["Tiranôu-Frostmourne","Dvalin-Frostmourne"]
  - name: Tobi
    chars: ["Dinkelheit-Antonidas","Klauwn-Antonidas"]
  - name: Tom
    chars: ["Schäppert-Anub'arak"]
  - name: Yasmin
    chars: ["Yäzmin-Antonidas","Crêpesuzette-Antonidas"]

raid:
  - date: 2023-11-15
    report: https://www.warcraftlogs.com/reports/yAav4BwKJjrVm2bk
    player: ['Dimi', 'Franzi', 'Joseph', 'Kalle', 'Kevin', 'Leon', 'Lutz', 'Marco', 'Marc', 'Micha', 'Mischa', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Tom', 'Yasmin']
  - date: 2023-11-19
    report: https://www.warcraftlogs.com/reports/C1xDZhXH2Pr6F7nR
    player: ['Carmen', 'Dimi', 'Franzi', 'Joseph', 'Kalle', 'Kevin', 'Leon', 'Lutz', 'Marco', 'Marc', 'Maxi', 'Micha', 'Mischa', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Tobi', 'Tom', 'Yasmin']
  - date: 2023-11-22
    report: https://www.warcraftlogs.com/reports/P9k8pfJrQ7ZycMgL
    player: ['Carmen', 'Franzi', 'Joseph', 'Kalle', 'Kevin', 'Leon', 'Lutz', 'Marco', 'Marc', 'Maxi', 'Micha', 'Mischa', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Tobi', 'Tom', 'Yasmin']
  - date: 2023-11-26
    report: https://www.warcraftlogs.com/reports/NxD74H2FGLb3mVRh
    player: ['Dennis', 'Dimi', 'Joseph', 'Kalle', 'Kevin', 'Marco', 'Marc', 'Micha', 'Mischa', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Tobi', 'Tom', 'Yasmin']
  - date: 2023-11-29
    report: https://www.warcraftlogs.com/reports/B6JXPT3Ycjqt9ND1
    player: ['Dave', 'Dimi', 'Franzi', 'Joseph', 'Kalle', 'Kevin', 'Leon', 'Lutz', 'Marc', 'Micha', 'Mischa', 'Olli', 'Tanja', 'Thomas', 'Tom', 'Yasmin']
  - date: 2023-12-03
    report: https://www.warcraftlogs.com/reports/awWJnDtgmVb8AxH4
    player: ['Dimi', 'Franzi', 'Joseph', 'Kalle', 'Kevin', 'Leon', 'Lutz', 'Marc', 'Maxi', 'Micha', 'Olli', 'Stephan', 'Tanja', 'Tobi', 'Tom', 'Yasmin']
  - date: 2023-12-06
    report: https://www.warcraftlogs.com/reports/QWnZwTKz8PyApxhd
    player: ['Carmen', 'Christoph', 'Dimi', 'Franzi', 'Joseph', 'Kalle', 'Kevin', 'Marc', 'Micha', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Tom', 'Yasmin']
  - date: 2023-12-10
    report: https://www.warcraftlogs.com/reports/mQYJGTMj2dzXPVyr
    player: ['Dimi', 'Franzi', 'Joseph', 'Kalle', 'Lutz', 'Marco', 'Marc', 'Micha', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Tobi', 'Tom']
  - date: 2023-12-13
    report: https://www.warcraftlogs.com/reports/6XfmYNygvqV84Htz
    player: [ 'Christoph', 'Dave', 'Dimi', 'Joseph', 'Kalle', 'Lutz', 'Marco', 'Marc', 'Micha', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Tom' ]
  - date: 2023-12-17
    report: https://www.warcraftlogs.com/reports/VXmAQFxvdk2cRDrt
    player: ['Dimi', 'Kalle', 'Lutz', 'Marc', 'Micha', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Tobi', 'Tom']
  - date: 2023-12-20
    report: https://www.warcraftlogs.com/reports/naMxQhwHjqZB3d2y
    player: ['Christoph', 'Dimi', 'Jessica', 'Kalle', 'Lutz', 'Marco', 'Marc', 'Micha', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Tobi']
  - date: 2023-12-27
    report: https://www.warcraftlogs.com/reports/JrYPGF9D1yLqtZhd
    player: ['Carmen', 'Christoph', 'Dave', 'Dimi', 'Joseph', 'Kalle', 'Kevin', 'Leon', 'Lutz', 'Maxi', 'Micha', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Yasmin']
  - date: 2024-01-03
    report: https://www.warcraftlogs.com/reports/YAwg4zvQ7PFGtVcq
    player: ['Christoph', 'Dave', 'Dimi', 'Joseph', 'Kalle', 'Kevin', 'Leon', 'Lutz', 'Marco', 'Marc', 'Micha', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Tom', 'Yasmin']
  - date: 2024-01-07
    report: https://www.warcraftlogs.com/reports/8B2ZXfVaYTqWzk7d
    player: ['Carmen', 'Christoph', 'Dimi', 'Kalle', 'Kevin', 'Lutz', 'Marc', 'Micha', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Tobi', 'Yasmin']
  - date: 2024-01-10
    report: https://www.warcraftlogs.com/reports/CMDTYL4HrFzwmjXR
    player: ['Carmen', 'Christoph', 'Kalle', 'Kevin', 'Leon', 'Lutz', 'Marco', 'Marc', 'Micha', 'Olli', 'Stephan', 'Thomas', 'Yasmin']
  - date: 2024-01-14
    report: https://www.warcraftlogs.com/reports/W4jyzhmN6nHkZ81f
    player: ['Carmen', 'Christoph', 'Dimi', 'Joseph', 'Kalle', 'Kevin', 'Leon', 'Lutz', 'Marco', 'Marc', 'Maxi', 'Micha', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Tobi', 'Yasmin']
  - date: 2024-01-17
    report: https://www.warcraftlogs.com/reports/X4zxpwFTJa386cfL
    player: ['Carmen', 'Christoph', 'Dimi', 'Joseph', 'Kalle', 'Kevin', 'Leon', 'Lutz', 'Marco', 'Marc', 'Maxi', 'Micha', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Yasmin']
  - date: 2024-01-21
    report: https://www.warcraftlogs.com/reports/WRwZnBN7JC2AGzKQ
    player: ['Carmen', 'Christoph', 'Dimi', 'Joseph', 'Kalle', 'Kevin', 'Lutz', 'Marco', 'Marc', 'Maxi', 'Micha', 'Olli', 'Stephan', 'Tanja', 'Tobi', 'Yasmin']
  - date: 2024-01-24
    report: https://www.warcraftlogs.com/reports/2nMYkQfm1GCt6pbV
    player: ['Carmen', 'Christoph', 'Kalle', 'Kevin', 'Leon', 'Marco', 'Marc', 'Micha', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Yasmin']
  - date: 2024-01-28
    report: https://www.warcraftlogs.com/reports/8gWbwtCPdQqKY72j
    player: ['Carmen', 'Christoph', 'Joseph', 'Kalle', 'Kevin', 'Lutz', 'Marco', 'Marc', 'Micha', 'Olli', 'Stephan', 'Thomas', 'Tobi', 'Yasmin']
  - date: 2024-01-31
    report: https://www.warcraftlogs.com/reports/FgtBdN9Kvmp1xknb
    player: ['Carmen', 'Christoph', 'Joseph', 'Kalle', 'Kevin', 'Lutz', 'Marco', 'Marc', 'Micha', 'Olli', 'Stephan', 'Tanja', 'Thomas', 'Yasmin']
  - date: 2024-02-07
    report: https://www.warcraftlogs.com/reports/2rCNvzQP9yJwWkdg
    player: ['Carmen', 'Christoph', 'Joseph', 'Kalle', 'Kevin', 'Lutz', 'Marco', 'Micha', 'Olli', 'Stephan', 'Thomas', 'Tobi']
  - date: 2024-02-18
    report: https://www.warcraftlogs.com/reports/BYPjJwazMCxNTVbp
    player: ['Carmen', 'Christoph', 'Janine', 'Kalle', 'Kevin', 'Lutz', 'Marco', 'Micha', 'Olli', 'Tanja', 'Thomas', 'Yasmin']
  - date: 2024-02-21
    report: https://www.warcraftlogs.com/reports/A9wgWR6ckLtyNaC3
    player: ['Carmen', 'Christoph', 'Janine', 'Joseph', 'Kalle', 'Kevin', 'Lutz', 'Marco', 'Micha', 'Olli', 'Tanja', 'Thomas', 'Tobi']
